os: linux
dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install .
  - pip install -r requirements-dev.txt

script:
  make travis

after_success:
  - bash <(curl -s https://codecov.io/bash)
